global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'my-project'

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]
